# Generated by Django 5.1.2 on 2024-10-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0002_blackjackgame_current_bet_blackjackgame_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackjackgame',
            name='current_bet',
        ),
        migrations.RemoveField(
            model_name='blackjackgame',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
