# Generated by Django 5.1.2 on 2024-10-09 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0003_remove_blackjackgame_current_bet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blackjackgame',
            name='bet_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blackjackgame',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blackjackgame',
            name='user_balance',
            field=models.IntegerField(default=1000),
        ),
    ]
