# Generated by Django 5.1.2 on 2024-10-09 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0004_blackjackgame_bet_amount_blackjackgame_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackjackgame',
            name='bet_amount',
        ),
        migrations.RemoveField(
            model_name='blackjackgame',
            name='user_balance',
        ),
        migrations.AddField(
            model_name='blackjackgame',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='blackjackgame',
            name='bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blackjackgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
