# Generated by Django 5.1.2 on 2024-10-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackjackgame',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='blackjackgame',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='blackjackgame',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
